name: release-docker-develop

on:
  push:
    branches:
      - main

concurrency: release-docker-develop

env:
  FORCE_COLOR: 1

jobs:
  release:
    runs-on: [self-hosted, arm64, cb]
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Get git commit
        id: git-commit
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> "$GITHUB_OUTPUT"
      - uses: ./.github/actions/docker-publish
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          tags: ghcr.io/kennethwussmann/docker-ffmpeg-converter:develop,ghcr.io/kennethwussmann/docker-ffmpeg-converter:${{ steps.git-commit.outputs.SHORT_SHA }}
          build-args: VERSION=${{ steps.git-commit.outputs.SHORT_SHA }}